### ISSUE TITLE
SEGV when using SHA3-512 in esdm_get_cpu_data_compress

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#19]
I use an old Haswell system which only supports RDRAND, if this should be of any influence here.

```
ESDM (22:39:23) (esdm-server) Debug - ESDM server [../frontends/server/server_main.c:install_term:189]: Install termination signal handler
ESDM (22:39:23) (esdm-server) Verbose - ESDM server [../frontends/server/server_main.c:daemon_init:142]: Starting ESDM server
ESDM (22:39:23) (esdm-server) Verbose [../esdm/esdm_builtin_hash_drbg.c:esdm_hash_drbg_alloc:55]: Hash DRBG core allocated
ESDM (22:39:23) (esdm-server) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_reset:136]: reset DRNG
ESDM (22:39:23) (esdm-server) Verbose - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_mgr_initialize:243]: DRNG with prediction resistance allocated
ESDM (22:39:23) (esdm-server) Verbose [../esdm/esdm_builtin_hash_drbg.c:esdm_hash_drbg_alloc:55]: Hash DRBG core allocated
ESDM (22:39:23) (esdm-server) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_reset:136]: reset DRNG
ESDM (22:39:23) (esdm-server) Verbose - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_mgr_initialize:251]: DRNG without prediction resistance allocated
ESDM (22:39:23) (esdm-server) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_mgr_initialize:258]: ESDM for general use is available
ESDM (22:39:23) (esdm-server) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_mgr_selftest:190]: Hash self test passed successfully
ESDM (22:39:23) (esdm-server) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_mgr_selftest:201]: DRNG self test passed successfully
ESDM (22:39:23) (esdm-server) Verbose - Entropy Source [../esdm/esdm_es_mgr.c:esdm_es_mgr_initialize:618]: Initialize ES manager
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_mgr.c:esdm_es_mgr_init_es:594]: Initialize ES Auxiliary
ESDM (22:39:23) (esdm-server) Verbose [../esdm/esdm_es_aux.c:esdm_aux_init:126]: Aux ES hash allocated
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_mgr.c:esdm_es_mgr_init_es:594]: Initialize ES Interrupt
ESDM (22:39:23) (esdm-server) Warning - Entropy Source [../esdm/esdm_es_irq.c:esdm_irq_initialize:150]: Disabling interrupt-based entropy source which is not present in kernel
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_mgr.c:esdm_es_mgr_init_es:594]: Initialize ES Scheduler
ESDM (22:39:23) (esdm-server) Warning - Entropy Source [../esdm/esdm_es_sched.c:esdm_sched_initialize:149]: Disabling scheduler-based entropy source which is not present in kernel
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_mgr.c:esdm_es_mgr_init_es:594]: Initialize ES JitterRNG
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_jent.c:esdm_jent_initialize:70]: Jitter RNG working on current system
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_mgr.c:esdm_es_mgr_init_es:594]: Initialize ES CPU
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_mgr.c:esdm_es_mgr_init_es:594]: Initialize ES KernelRNG
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_mgr.c:esdm_es_mgr_init_es:594]: Initialize ES LinuxHWRand
ESDM (22:39:23) (esdm-server) Debug [../esdm/es_cpu/cpu_random_x86.h:cpu_es_x86_rdseed:96]: RDSEED support not detected
ESDM (22:39:23) (esdm-server) Debug [../esdm/es_cpu/cpu_random_x86.h:cpu_es_x86_rdrand:119]: RDRAND support detected
ESDM (22:39:23) (esdm-server) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_seed_work_one:486]: reseed triggered by system events for DRNG on node 0
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_jent.c:esdm_jent_get:122]: obtained 256 bits of entropy from Jitter RNG noise source
ESDM (22:39:23) (esdm-server) Debug [../esdm/es_cpu/cpu_random_x86.h:cpu_es_x86_rdseed:96]: RDSEED support not detected
ESDM (22:39:23) (esdm-server) Debug - Entropy Source [../esdm/esdm_es_cpu.c:esdm_cpu_multiplier:181]: Setting CPU ES multiplier to 512
ESDM (22:39:23) (esdm-server) Debug [../esdm/es_cpu/cpu_random_x86.h:cpu_es_x86_rdrand:119]: RDRAND support detected

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fb01b2 in esdm_get_cpu_data_compress (multiplier=<optimized out>, requested_bits=256, 
    outbuf=0x7fffffffc88c "\207h\376\b\356Ľ\030Ґiz\351\345\002\3775Q\202\347-(\241cA/\023l\020|\301", <incomplete sequence \355>) at ../esdm/esdm_es_cpu.c:122
122			if (hash_cb->hash_update(shash, outbuf, ent_bits >> 3))
(gdb) bt
#0  0x00007ffff7fb01b2 in esdm_get_cpu_data_compress (multiplier=<optimized out>, requested_bits=256, 
    outbuf=0x7fffffffc88c "\207h\376\b\356Ľ\030Ґiz\351\345\002\3775Q\202\347-(\241cA/\023l\020|\301", <incomplete sequence \355>) at ../esdm/esdm_es_cpu.c:122
#1  esdm_cpu_get (eb_es=0x7fffffffc88c, requested_bits=<optimized out>, unsused=<optimized out>) at ../esdm/esdm_es_cpu.c:225
#2  0x00007ffff7faecfb in esdm_fill_seed_buffer (eb=<optimized out>, requested_bits=64, force=<optimized out>) at ../esdm/esdm_es_mgr.c:728
#3  0x00007ffff7fac89c in esdm_drng_seed_es_nolock (drng=drng@entry=0x7ffff7fba140 <esdm_drng_init>, drng_type=0x7ffff7fb3a31 "regular", init_ops=true)
    at ../esdm/esdm_drng_mgr.c:416
#4  0x00007ffff7face5e in esdm_drng_seed_es (drng=0x7ffff7fba140 <esdm_drng_init>) at ../esdm/esdm_drng_mgr.c:469
#5  esdm_drng_seed (drng=0x7ffff7fba140 <esdm_drng_init>) at ../esdm/esdm_drng_mgr.c:479
#6  esdm_drng_seed_work_one (drng=drng@entry=0x7ffff7fba140 <esdm_drng_init>, node=node@entry=0) at ../esdm/esdm_drng_mgr.c:489
#7  0x00007ffff7facf76 in __esdm_drng_seed_work (force=true) at ../esdm/esdm_drng_mgr.c:543
#8  __esdm_drng_seed_work (force=<optimized out>) at ../esdm/esdm_drng_mgr.c:496
#9  0x00007ffff7fad0c7 in esdm_force_fully_seeded () at ../esdm/esdm_drng_mgr.c:791
#10 esdm_force_fully_seeded () at ../esdm/esdm_drng_mgr.c:785
#11 0x00007ffff7faea9b in esdm_es_mgr_initialize () at ../esdm/esdm_es_mgr.c:645
#12 0x00007ffff7faf0db in esdm_init () at ../esdm/esdm_lib.c:45
#13 0x00005555555598ca in daemon_init () at ../frontends/server/server_main.c:143
#14 main (argc=<optimized out>, argv=<optimized out>) at ../frontends/server/server_main.c:294
```

**Comment by thillux** [comment]
I disabled both kernel sources, in order to rule them out as failure influences.

**Comment by thillux** [comment]
Basic idea of possible fix:

```
diff --git a/esdm/esdm_es_cpu.c b/esdm/esdm_es_cpu.c
index fe6343a..11f6d92 100644
--- a/esdm/esdm_es_cpu.c
+++ b/esdm/esdm_es_cpu.c
@@ -85,7 +85,13 @@ static uint32_t
 esdm_get_cpu_data_compress(uint8_t *outbuf, uint32_t requested_bits,
                           uint32_t multiplier)
 {
+#if defined(ESDM_HASH_SHA512)
        LC_HASH_CTX_ON_STACK(shash, lc_sha512);
+#elif defined(ESDM_HASH_SHA3_512)
+       LC_HASH_CTX_ON_STACK(shash, lc_sha3_512);
+#else
+#error "Unknown default hash selected"
+#endif
        const struct esdm_hash_cb *hash_cb;
        struct esdm_drng *drng = esdm_drng_node_instance();
        uint32_t ent_bits = 0, i, partial_bits = 0, digestsize, digestsize_bits,

```

**Comment by smuellerDD** [comment]
That is the fix :-) 
Though, a slight update was needed which is now applied.
